import {
    AQUISITION_CAME_BY_COOK_RECOMMENDATION,
    COOK_RECOMMENDATION_API,
    CUSTOMER_PROFILE_PAGE_API,
    MAP_CUSTOMER_SUPPLY_PHONE_API,
    OTP_API,
    PLACE_REQUEST_API,
    RATING_SUBMIT_API,
    SUBMIT_CALL_STATUS_API,
    X_AUTH_HEADER,
    X_AUTH_TOKEN,
    X_ROLE_HEADER
} from "../Constants";
import {Platform} from "react-native";


// Your API calls here
